//
//  DatabaseController.swift
//  Sm4shGames
//
//  Created by Test on 1/11/19.
//  Copyright © 2019 DavidF. All rights reserved.
//

import Foundation
import CouchbaseLiteSwift

class DatabaseController {
    
    // MARK: - Properties
    
    static let shared = DatabaseController()
    
    let database: Database

    private init() {
        
        // Get the database (and create it if it doesn’t exist).
        
        do {
            self.database = try Database(name: "sm4shDB")
        } catch {
            fatalError("Error opening database")
        }
        
    }
    
    
    public func createDoc() -> MutableDocument{
        
        // Create a new document (i.e. a record) in the database.
        let mutableDoc = MutableDocument()
            .setFloat(2.0, forKey: "version")
            .setString("SDK", forKey: "type")
        
        // Save it to the database.
        do {
            try self.database.saveDocument(mutableDoc)
        } catch {
            fatalError("Error saving document")
        }
        
        return mutableDoc
    }
    
    public func updateDoc(doc: MutableDocument){
        
        // Update a document.
        
        if let mutableDoc = self.database.dou{
            mutableDoc.setString("Swift", forKey: "language")
            do {
                try self.database.saveDocument(mutableDoc)
                
                let document = self.database.document(withID: doc.id)!
                // Log the document ID (generated by the database)
                // and properties
                print("Document ID :: \(document.id)")
                print("Learning \(document.string(forKey: "language")!)")
                print("Learning \(document.string(forKey: "type")!)")
            } catch {
                fatalError("Error updating document")
            }
        }
        
    }
    
}
